import os
import sys

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.db.database import SessionLocal
from app.models import Confederation, NationalTeam

def seed():
    db = SessionLocal()
    
    confeds = {
        "UEFA": {"name": "UEFA", "code": "UEFA"},
        "CONMEBOL": {"name": "CONMEBOL", "code": "CONMEBOL"},
        "CONCACAF": {"name": "CONCACAF", "code": "CONCACAF"},
        "CAF": {"name": "CAF", "code": "CAF"},
        "AFC": {"name": "AFC", "code": "AFC"},
        "OFC": {"name": "OFC", "code": "OFC"},
    }
    
    for c in confeds.values():
        if not db.query(Confederation).filter_by(code=c["code"]).first():
            db.add(Confederation(**c))
    db.commit()

    db_confeds = {c.code: c.id for c in db.query(Confederation).all()}

    teams_data = [
        # CONMEBOL (10)
        ("Argentina", "ARG", "ARG", "CONMEBOL", 1, 95.0),
        ("Brazil", "BRA", "BRA", "CONMEBOL", 3, 92.0),
        ("Uruguay", "URU", "URU", "CONMEBOL", 11, 85.0),
        ("Colombia", "COL", "COL", "CONMEBOL", 14, 83.0),
        ("Ecuador", "ECU", "ECU", "CONMEBOL", 31, 78.0),
        ("Peru", "PER", "PER", "CONMEBOL", 35, 75.0),
        ("Chile", "CHI", "CHI", "CONMEBOL", 40, 74.0),
        ("Venezuela", "VEN", "VEN", "CONMEBOL", 49, 72.0),
        ("Paraguay", "PAR", "PAR", "CONMEBOL", 53, 71.0),
        ("Bolivia", "BOL", "BOL", "CONMEBOL", 85, 65.0),
        
        # UEFA (55)
        ("France", "FRA", "FRA", "UEFA", 2, 94.0),
        ("England", "ENG", "ENG", "UEFA", 4, 91.0),
        ("Belgium", "BEL", "BEL", "UEFA", 5, 88.0),
        ("Croatia", "CRO", "CRO", "UEFA", 6, 86.0),
        ("Netherlands", "NED", "NED", "UEFA", 7, 87.0),
        ("Portugal", "POR", "POR", "UEFA", 8, 89.0),
        ("Italy", "ITA", "ITA", "UEFA", 9, 87.0),
        ("Spain", "ESP", "ESP", "UEFA", 10, 88.0),
        ("Germany", "GER", "GER", "UEFA", 15, 86.0),
        ("Switzerland", "SUI", "SUI", "UEFA", 16, 82.0),
        ("Denmark", "DEN", "DEN", "UEFA", 19, 81.0),
        ("Austria", "AUT", "AUT", "UEFA", 25, 78.0),
        ("Sweden", "SWE", "SWE", "UEFA", 26, 77.0),
        ("Poland", "POL", "POL", "UEFA", 30, 76.0),
        ("Serbia", "SRB", "SRB", "UEFA", 32, 79.0),
        ("Wales", "WAL", "WAL", "UEFA", 33, 74.0),
        ("Scotland", "SCO", "SCO", "UEFA", 36, 73.0),
        ("Turkey", "TUR", "TUR", "UEFA", 38, 77.0),
        ("Czech Republic", "CZE", "CZE", "UEFA", 39, 75.0),
        ("Romania", "ROU", "ROU", "UEFA", 43, 72.0),
        ("Norway", "NOR", "NOR", "UEFA", 44, 76.0),
        ("Slovakia", "SVK", "SVK", "UEFA", 45, 71.0),
        ("Greece", "GRE", "GRE", "UEFA", 47, 72.0),
        ("Ireland", "IRL", "IRL", "UEFA", 58, 69.0),
        ("Finland", "FIN", "FIN", "UEFA", 59, 68.0),
        ("Albania", "ALB", "ALB", "UEFA", 62, 67.0),
        ("Iceland", "ISL", "ISL", "UEFA", 67, 65.0),
        ("North Macedonia", "MKD", "MKD", "UEFA", 68, 64.0),
        ("Bosnia and Herzegovina", "BIH", "BIH", "UEFA", 69, 66.0),
        ("Georgia", "GEO", "GEO", "UEFA", 77, 66.0),
        ("Israel", "ISR", "ISR", "UEFA", 71, 65.0),
        ("Bulgaria", "BUL", "BUL", "UEFA", 83, 63.0),
        ("Armenia", "ARM", "ARM", "UEFA", 93, 61.0),
        ("Kosovo", "KOS", "KOS", "UEFA", 101, 60.0),
        ("Kazakhstan", "KAZ", "KAZ", "UEFA", 100, 60.0),
        ("Montenegro", "MNE", "MNE", "UEFA", 72, 64.0),
        ("Northern Ireland", "NIR", "NIR", "UEFA", 74, 63.0),
        ("Slovenia", "SVN", "SVN", "UEFA", 54, 70.0),
        ("Hungary", "HUN", "HUN", "UEFA", 27, 76.0),
        ("Estonia", "EST", "EST", "UEFA", 118, 55.0),
        ("Latvia", "LVA", "LVA", "UEFA", 137, 52.0),
        ("Lithuania", "LTU", "LTU", "UEFA", 134, 53.0),
        ("Moldova", "MDA", "MDA", "UEFA", 155, 48.0),
        ("Cyprus", "CYP", "CYP", "UEFA", 125, 54.0),
        ("Azerbaijan", "AZE", "AZE", "UEFA", 114, 56.0),
        ("Belarus", "BLR", "BLR", "UEFA", 95, 60.0),
        ("Faroe Islands", "FRO", "FRO", "UEFA", 135, 53.0),
        ("Liechtenstein", "LIE", "LIE", "UEFA", 203, 30.0),
        ("Luxembourg", "LUX", "LUX", "UEFA", 87, 62.0),
        ("Malta", "MLT", "MLT", "UEFA", 171, 42.0),
        ("Andorra", "AND", "AND", "UEFA", 164, 45.0),
        ("San Marino", "SMR", "SMR", "UEFA", 211, 25.0),
        ("Gibraltar", "GIB", "GIB", "UEFA", 201, 31.0),
        ("Russia", "RUS", "RUS", "UEFA", 35, 76.0),

        # CONCACAF (41)
        ("USA", "USA", "USA", "CONCACAF", 11, 81.0),
        ("Mexico", "MEX", "MEX", "CONCACAF", 15, 80.0),
        ("Canada", "CAN", "CAN", "CONCACAF", 48, 75.0),
        ("Costa Rica", "CRC", "CRC", "CONCACAF", 52, 73.0),
        ("Panama", "PAN", "PAN", "CONCACAF", 41, 74.0),
        ("Jamaica", "JAM", "JAM", "CONCACAF", 55, 72.0),
        ("Honduras", "HON", "HON", "CONCACAF", 76, 67.0),
        ("El Salvador", "SLV", "SLV", "CONCACAF", 78, 66.0),
        ("Haiti", "HAI", "HAI", "CONCACAF", 89, 64.0),
        ("Curacao", "CUW", "CUW", "CONCACAF", 90, 63.0),
        ("Trinidad and Tobago", "TRI", "TRI", "CONCACAF", 98, 61.0),
        ("Guatemala", "GUA", "GUA", "CONCACAF", 108, 59.0),
        ("Nicaragua", "NCA", "NCA", "CONCACAF", 134, 52.0),
        ("Suriname", "SUR", "SUR", "CONCACAF", 143, 50.0),
        ("Antigua and Barbuda", "ATG", "ATG", "CONCACAF", 142, 50.0),
        ("Dominican Republic", "DOM", "DOM", "CONCACAF", 150, 48.0),
        ("Cuba", "CUB", "CUB", "CONCACAF", 169, 43.0),
        ("Bermuda", "BER", "BER", "CONCACAF", 171, 42.0),
        ("Puerto Rico", "PUR", "PUR", "CONCACAF", 160, 46.0),
        ("Guyana", "GUY", "GUY", "CONCACAF", 157, 47.0),
        ("Belize", "BLZ", "BLZ", "CONCACAF", 182, 38.0),
        ("Barbados", "BRB", "BRB", "CONCACAF", 178, 39.0),
        ("Saint Kitts and Nevis", "SKN", "SKN", "CONCACAF", 147, 49.0),
        ("Saint Lucia", "LCA", "LCA", "CONCACAF", 167, 44.0),
        ("Saint Vincent and the Grenadines", "VIN", "VIN", "CONCACAF", 173, 41.0),
        ("Grenada", "GRN", "GRN", "CONCACAF", 174, 40.0),
        ("Dominica", "DMA", "DMA", "CONCACAF", 180, 39.0),
        ("Cayman Islands", "CAY", "CAY", "CONCACAF", 197, 32.0),
        ("Montserrat", "MSR", "MSR", "CONCACAF", 176, 40.0),
        ("Bahamas", "BAH", "BAH", "CONCACAF", 202, 30.0),
        ("Aruba", "ARU", "ARU", "CONCACAF", 193, 34.0),
        ("Turks and Caicos Islands", "TCA", "TCA", "CONCACAF", 206, 28.0),
        ("US Virgin Islands", "VIR", "VIR", "CONCACAF", 208, 27.0),
        ("British Virgin Islands", "VGB", "VGB", "CONCACAF", 207, 27.0),
        ("Anguilla", "AIA", "AIA", "CONCACAF", 209, 26.0),
        ("French Guiana", "GUF", "GUF", "CONCACAF", 210, 50.0),
        ("Martinique", "MTQ", "MTQ", "CONCACAF", 211, 52.0),
        ("Guadeloupe", "GLP", "GLP", "CONCACAF", 212, 50.0),
        ("Bonaire", "BOE", "BOE", "CONCACAF", 213, 30.0),
        ("Saint Martin", "SMT", "SMT", "CONCACAF", 214, 28.0),
        ("Sint Maarten", "SXM", "SXM", "CONCACAF", 215, 27.0),

        # CAF (54)
        ("Morocco", "MAR", "MAR", "CAF", 12, 84.0),
        ("Senegal", "SEN", "SEN", "CAF", 20, 81.0),
        ("Nigeria", "NGA", "NGA", "CAF", 28, 78.0),
        ("Egypt", "EGY", "EGY", "CAF", 34, 76.0),
        ("Ivory Coast", "CIV", "CIV", "CAF", 37, 75.0),
        ("Tunisia", "TUN", "TUN", "CAF", 41, 74.0),
        ("Algeria", "ALG", "ALG", "CAF", 43, 74.0),
        ("Mali", "MLI", "MLI", "CAF", 47, 72.0),
        ("Cameroon", "CMR", "CMR", "CAF", 51, 71.0),
        ("South Africa", "RSA", "RSA", "CAF", 58, 69.0),
        ("Burkina Faso", "BFA", "BFA", "CAF", 61, 68.0),
        ("DR Congo", "COD", "COD", "CAF", 63, 67.0),
        ("Cape Verde", "CPV", "CPV", "CAF", 65, 66.0),
        ("Ghana", "GHA", "GHA", "CAF", 67, 65.0),
        ("Guinea", "GUI", "GUI", "CAF", 76, 64.0),
        ("Equatorial Guinea", "EQG", "EQG", "CAF", 79, 63.0),
        ("Gabon", "GAB", "GAB", "CAF", 84, 62.0),
        ("Zambia", "ZAM", "ZAM", "CAF", 87, 61.0),
        ("Uganda", "UGA", "UGA", "CAF", 92, 60.0),
        ("Angola", "ANG", "ANG", "CAF", 94, 60.0),
        ("Benin", "BEN", "BEN", "CAF", 97, 59.0),
        ("Namibia", "NAM", "NAM", "CAF", 106, 57.0),
        ("Mauritania", "MTN", "MTN", "CAF", 105, 57.0),
        ("Madagascar", "MAD", "MAD", "CAF", 109, 56.0),
        ("Mozambique", "MOZ", "MOZ", "CAF", 110, 56.0),
        ("Kenya", "KEN", "KEN", "CAF", 111, 56.0),
        ("Congo", "CGO", "CGO", "CAF", 112, 55.0),
        ("Togo", "TOG", "TOG", "CAF", 116, 54.0),
        ("Tanzania", "TAN", "TAN", "CAF", 119, 53.0),
        ("Guinea-Bissau", "GNB", "GNB", "CAF", 118, 53.0),
        ("Zimbabwe", "ZIM", "ZIM", "CAF", 124, 52.0),
        ("Malawi", "MWI", "MWI", "CAF", 122, 52.0),
        ("Libya", "LBY", "LBY", "CAF", 120, 53.0),
        ("Comoros", "COM", "COM", "CAF", 117, 54.0),
        ("Sierra Leone", "SLE", "SLE", "CAF", 126, 51.0),
        ("Sudan", "SDN", "SDN", "CAF", 127, 51.0),
        ("Central African Republic", "CTA", "CTA", "CAF", 129, 50.0),
        ("Niger", "NIG", "NIG", "CAF", 128, 50.0),
        ("Rwanda", "RWA", "RWA", "CAF", 131, 49.0),
        ("Gambia", "GAM", "GAM", "CAF", 130, 50.0),
        ("Burundi", "BDI", "BDI", "CAF", 140, 47.0),
        ("Ethiopia", "ETH", "ETH", "CAF", 145, 46.0),
        ("Botswana", "BOT", "BOT", "CAF", 146, 46.0),
        ("Liberia", "LBR", "LBR", "CAF", 152, 45.0),
        ("Eswatini", "SWZ", "SWZ", "CAF", 148, 45.0),
        ("Lesotho", "LES", "LES", "CAF", 149, 45.0),
        ("South Sudan", "SSD", "SSD", "CAF", 167, 41.0),
        ("Mauritius", "MRI", "MRI", "CAF", 177, 39.0),
        ("Chad", "CHA", "CHA", "CAF", 176, 39.0),
        ("Sao Tome and Principe", "STP", "STP", "CAF", 191, 35.0),
        ("Djibouti", "DJI", "DJI", "CAF", 192, 34.0),
        ("Seychelles", "SEY", "SEY", "CAF", 199, 31.0),
        ("Eritrea", "ERI", "ERI", "CAF", 200, 30.0),
        ("Somalia", "SOM", "SOM", "CAF", 198, 31.0),

        # AFC (46)
        ("Japan", "JPN", "JPN", "AFC", 18, 83.0),
        ("Iran", "IRN", "IRN", "AFC", 20, 81.0),
        ("South Korea", "KOR", "KOR", "AFC", 22, 80.0),
        ("Australia", "AUS", "AUS", "AFC", 23, 79.0),
        ("Qatar", "QAT", "QAT", "AFC", 34, 76.0),
        ("Saudi Arabia", "KSA", "KSA", "AFC", 53, 71.0),
        ("Iraq", "IRQ", "IRQ", "AFC", 59, 69.0),
        ("Uzbekistan", "UZB", "UZB", "AFC", 66, 66.0),
        ("UAE", "UAE", "UAE", "AFC", 69, 65.0),
        ("Jordan", "JOR", "JOR", "AFC", 71, 64.0),
        ("Oman", "OMA", "OMA", "AFC", 80, 62.0),
        ("Bahrain", "BHR", "BHR", "AFC", 82, 62.0),
        ("China", "CHN", "CHN", "AFC", 88, 61.0),
        ("Syria", "SYR", "SYR", "AFC", 89, 60.0),
        ("Palestine", "PLE", "PLE", "AFC", 93, 60.0),
        ("Tajikistan", "TJK", "TJK", "AFC", 99, 58.0),
        ("Thailand", "THA", "THA", "AFC", 101, 58.0),
        ("Kyrgyzstan", "KGZ", "KGZ", "AFC", 104, 57.0),
        ("Vietnam", "VIE", "VIE", "AFC", 115, 54.0),
        ("North Korea", "PRK", "PRK", "AFC", 118, 53.0),
        ("Lebanon", "LBN", "LBN", "AFC", 120, 52.0),
        ("India", "IND", "IND", "AFC", 121, 52.0),
        ("Malaysia", "MAS", "MAS", "AFC", 138, 48.0),
        ("Kuwait", "KUW", "KUW", "AFC", 139, 48.0),
        ("Philippines", "PHI", "PHI", "AFC", 141, 47.0),
        ("Turkmenistan", "TKM", "TKM", "AFC", 143, 46.0),
        ("Indonesia", "IDN", "IDN", "AFC", 134, 49.0),
        ("Afghanistan", "AFG", "AFG", "AFC", 151, 44.0),
        ("Singapore", "SGP", "SGP", "AFC", 155, 43.0),
        ("Myanmar", "MYA", "MYA", "AFC", 163, 41.0),
        ("Yemen", "YEM", "YEM", "AFC", 156, 42.0),
        ("Hong Kong", "HKG", "HKG", "AFC", 157, 42.0),
        ("Chinese Taipei", "TPE", "TPE", "AFC", 159, 42.0),
        ("Maldives", "MDV", "MDV", "AFC", 161, 41.0),
        ("Nepal", "NEP", "NEP", "AFC", 175, 38.0),
        ("Cambodia", "CAM", "CAM", "AFC", 179, 37.0),
        ("Bangladesh", "BAN", "BAN", "AFC", 184, 36.0),
        ("Bhutan", "BHU", "BHU", "AFC", 185, 35.0),
        ("Macau", "MAC", "MAC", "AFC", 187, 34.0),
        ("Mongolia", "MNG", "MNG", "AFC", 191, 33.0),
        ("Laos", "LAO", "LAO", "AFC", 190, 34.0),
        ("Brunei", "BRU", "BRU", "AFC", 194, 32.0),
        ("Pakistan", "PAK", "PAK", "AFC", 195, 31.0),
        ("Timor-Leste", "TLS", "TLS", "AFC", 198, 30.0),
        ("Sri Lanka", "SRI", "SRI", "AFC", 204, 28.0),
        ("Guam", "GUM", "GUM", "AFC", 205, 28.0),

        # OFC (11)
        ("New Zealand", "NZL", "NZL", "OFC", 104, 57.0),
        ("Solomon Islands", "SOL", "SOL", "OFC", 132, 49.0),
        ("Fiji", "FIJ", "FIJ", "OFC", 168, 41.0),
        ("New Caledonia", "NCL", "NCL", "OFC", 158, 43.0),
        ("Tahiti", "TAH", "TAH", "OFC", 162, 42.0),
        ("Vanuatu", "VAN", "VAN", "OFC", 170, 40.0),
        ("Papua New Guinea", "PNG", "PNG", "OFC", 165, 41.0),
        ("Samoa", "SAM", "SAM", "OFC", 186, 35.0),
        ("American Samoa", "ASA", "ASA", "OFC", 188, 34.0),
        ("Cook Islands", "COK", "COK", "OFC", 189, 34.0),
        ("Tonga", "TGA", "TGA", "OFC", 196, 31.0),
    ]

    for name, short_name, fifa_code, confed_code, ranking, rating in teams_data:
        if not db.query(NationalTeam).filter_by(fifa_code=fifa_code).first():
            db.add(NationalTeam(
                name=name,
                short_name=short_name,
                fifa_code=fifa_code,
                confederation_id=db_confeds[confed_code],
                fifa_ranking=ranking,
                simulation_rating=rating
            ))
    
    db.commit()
    db.close()
    print(f"Seeded {len(teams_data)} teams and 6 confederations.")

if __name__ == "__main__":
    seed()
