import { MongoClient } from 'mongodb';

async function seed() {
  const uri = process.env.MONGO_URL || 'mongodb://localhost:27017';
  const client = new MongoClient(uri);

  try {
    await client.connect();
    console.log('Database connected');

    const db = client.db('simulator-soccer');
    const teamColl = db.collection('national_teams');

    // Clear old data to rebuild schema structure
    await teamColl.deleteMany({});
    await db.collection('tournaments').deleteMany({});

    const confedNames: Record<string, string> = {
      UEFA: 'UEFA',
      CONMEBOL: 'CONMEBOL',
      CONCACAF: 'CONCACAF',
      CAF: 'CAF',
      AFC: 'AFC',
      OFC: 'OFC',
    };

    interface TeamData {
      name: string;
      shortName: string;
      fifaCode: string;
      confed: string;
      ranking: number;
      rating: number;
    }

    const teamsData: TeamData[] = [
      { name: 'Argentina', shortName: 'ARG', fifaCode: 'ARG', confed: 'CONMEBOL', ranking: 1, rating: 95 },
      { name: 'Brazil', shortName: 'BRA', fifaCode: 'BRA', confed: 'CONMEBOL', ranking: 3, rating: 92 },
      { name: 'Uruguay', shortName: 'URU', fifaCode: 'URU', confed: 'CONMEBOL', ranking: 11, rating: 85 },
      { name: 'Colombia', shortName: 'COL', fifaCode: 'COL', confed: 'CONMEBOL', ranking: 14, rating: 83 },
      { name: 'Ecuador', shortName: 'ECU', fifaCode: 'ECU', confed: 'CONMEBOL', ranking: 31, rating: 78 },
      { name: 'Peru', shortName: 'PER', fifaCode: 'PER', confed: 'CONMEBOL', ranking: 35, rating: 75 },
      { name: 'Chile', shortName: 'CHI', fifaCode: 'CHI', confed: 'CONMEBOL', ranking: 40, rating: 74 },
      { name: 'Venezuela', shortName: 'VEN', fifaCode: 'VEN', confed: 'CONMEBOL', ranking: 49, rating: 72 },
      { name: 'Paraguay', shortName: 'PAR', fifaCode: 'PAR', confed: 'CONMEBOL', ranking: 53, rating: 71 },
      { name: 'Bolivia', shortName: 'BOL', fifaCode: 'BOL', confed: 'CONMEBOL', ranking: 85, rating: 65 },
      { name: 'France', shortName: 'FRA', fifaCode: 'FRA', confed: 'UEFA', ranking: 2, rating: 94 },
      { name: 'England', shortName: 'ENG', fifaCode: 'ENG', confed: 'UEFA', ranking: 4, rating: 91 },
      { name: 'Belgium', shortName: 'BEL', fifaCode: 'BEL', confed: 'UEFA', ranking: 5, rating: 88 },
      { name: 'Croatia', shortName: 'CRO', fifaCode: 'CRO', confed: 'UEFA', ranking: 6, rating: 86 },
      { name: 'Netherlands', shortName: 'NED', fifaCode: 'NED', confed: 'UEFA', ranking: 7, rating: 87 },
      { name: 'Portugal', shortName: 'POR', fifaCode: 'POR', confed: 'UEFA', ranking: 8, rating: 89 },
      { name: 'Italy', shortName: 'ITA', fifaCode: 'ITA', confed: 'UEFA', ranking: 9, rating: 87 },
      { name: 'Spain', shortName: 'ESP', fifaCode: 'ESP', confed: 'UEFA', ranking: 10, rating: 88 },
      { name: 'Germany', shortName: 'GER', fifaCode: 'GER', confed: 'UEFA', ranking: 15, rating: 86 },
      { name: 'Switzerland', shortName: 'SUI', fifaCode: 'SUI', confed: 'UEFA', ranking: 16, rating: 82 },
      { name: 'Denmark', shortName: 'DEN', fifaCode: 'DEN', confed: 'UEFA', ranking: 19, rating: 81 },
      { name: 'Austria', shortName: 'AUT', fifaCode: 'AUT', confed: 'UEFA', ranking: 25, rating: 78 },
      { name: 'Sweden', shortName: 'SWE', fifaCode: 'SWE', confed: 'UEFA', ranking: 26, rating: 77 },
      { name: 'Poland', shortName: 'POL', fifaCode: 'POL', confed: 'UEFA', ranking: 30, rating: 76 },
      { name: 'Serbia', shortName: 'SRB', fifaCode: 'SRB', confed: 'UEFA', ranking: 32, rating: 79 },
      { name: 'Wales', shortName: 'WAL', fifaCode: 'WAL', confed: 'UEFA', ranking: 33, rating: 74 },
      { name: 'Scotland', shortName: 'SCO', fifaCode: 'SCO', confed: 'UEFA', ranking: 36, rating: 73 },
      { name: 'Turkey', shortName: 'TUR', fifaCode: 'TUR', confed: 'UEFA', ranking: 38, rating: 77 },
      { name: 'Czech Republic', shortName: 'CZE', fifaCode: 'CZE', confed: 'UEFA', ranking: 39, rating: 75 },
      { name: 'Romania', shortName: 'ROU', fifaCode: 'ROU', confed: 'UEFA', ranking: 43, rating: 72 },
      { name: 'Norway', shortName: 'NOR', fifaCode: 'NOR', confed: 'UEFA', ranking: 44, rating: 76 },
      { name: 'Slovakia', shortName: 'SVK', fifaCode: 'SVK', confed: 'UEFA', ranking: 45, rating: 71 },
      { name: 'Greece', shortName: 'GRE', fifaCode: 'GRE', confed: 'UEFA', ranking: 47, rating: 72 },
      { name: 'Ireland', shortName: 'IRL', fifaCode: 'IRL', confed: 'UEFA', ranking: 58, rating: 69 },
      { name: 'Finland', shortName: 'FIN', fifaCode: 'FIN', confed: 'UEFA', ranking: 59, rating: 68 },
      { name: 'Albania', shortName: 'ALB', fifaCode: 'ALB', confed: 'UEFA', ranking: 62, rating: 67 },
      { name: 'Iceland', shortName: 'ISL', fifaCode: 'ISL', confed: 'UEFA', ranking: 67, rating: 65 },
      { name: 'North Macedonia', shortName: 'MKD', fifaCode: 'MKD', confed: 'UEFA', ranking: 68, rating: 64 },
      { name: 'Bosnia and Herzegovina', shortName: 'BIH', fifaCode: 'BIH', confed: 'UEFA', ranking: 69, rating: 66 },
      { name: 'Georgia', shortName: 'GEO', fifaCode: 'GEO', confed: 'UEFA', ranking: 77, rating: 66 },
      { name: 'Israel', shortName: 'ISR', fifaCode: 'ISR', confed: 'UEFA', ranking: 71, rating: 65 },
      { name: 'Bulgaria', shortName: 'BUL', fifaCode: 'BUL', confed: 'UEFA', ranking: 83, rating: 63 },
      { name: 'Armenia', shortName: 'ARM', fifaCode: 'ARM', confed: 'UEFA', ranking: 93, rating: 61 },
      { name: 'Kosovo', shortName: 'KOS', fifaCode: 'KOS', confed: 'UEFA', ranking: 101, rating: 60 },
      { name: 'Kazakhstan', shortName: 'KAZ', fifaCode: 'KAZ', confed: 'UEFA', ranking: 100, rating: 60 },
      { name: 'Montenegro', shortName: 'MNE', fifaCode: 'MNE', confed: 'UEFA', ranking: 72, rating: 64 },
      { name: 'Northern Ireland', shortName: 'NIR', fifaCode: 'NIR', confed: 'UEFA', ranking: 74, rating: 63 },
      { name: 'Slovenia', shortName: 'SVN', fifaCode: 'SVN', confed: 'UEFA', ranking: 54, rating: 70 },
      { name: 'Hungary', shortName: 'HUN', fifaCode: 'HUN', confed: 'UEFA', ranking: 27, rating: 76 },
      { name: 'Estonia', shortName: 'EST', fifaCode: 'EST', confed: 'UEFA', ranking: 118, rating: 55 },
      { name: 'Latvia', shortName: 'LVA', fifaCode: 'LVA', confed: 'UEFA', ranking: 137, rating: 52 },
      { name: 'Lithuania', shortName: 'LTU', fifaCode: 'LTU', confed: 'UEFA', ranking: 134, rating: 53 },
      { name: 'Moldova', shortName: 'MDA', fifaCode: 'MDA', confed: 'UEFA', ranking: 155, rating: 48 },
      { name: 'Cyprus', shortName: 'CYP', fifaCode: 'CYP', confed: 'UEFA', ranking: 125, rating: 54 },
      { name: 'Azerbaijan', shortName: 'AZE', fifaCode: 'AZE', confed: 'UEFA', ranking: 114, rating: 56 },
      { name: 'Belarus', shortName: 'BLR', fifaCode: 'BLR', confed: 'UEFA', ranking: 95, rating: 60 },
      { name: 'Faroe Islands', shortName: 'FRO', fifaCode: 'FRO', confed: 'UEFA', ranking: 135, rating: 53 },
      { name: 'Liechtenstein', shortName: 'LIE', fifaCode: 'LIE', confed: 'UEFA', ranking: 203, rating: 30 },
      { name: 'Luxembourg', shortName: 'LUX', fifaCode: 'LUX', confed: 'UEFA', ranking: 87, rating: 62 },
      { name: 'Malta', shortName: 'MLT', fifaCode: 'MLT', confed: 'UEFA', ranking: 171, rating: 42 },
      { name: 'Andorra', shortName: 'AND', fifaCode: 'AND', confed: 'UEFA', ranking: 164, rating: 45 },
      { name: 'San Marino', shortName: 'SMR', fifaCode: 'SMR', confed: 'UEFA', ranking: 211, rating: 25 },
      { name: 'Gibraltar', shortName: 'GIB', fifaCode: 'GIB', confed: 'UEFA', ranking: 201, rating: 31 },
      { name: 'Russia', shortName: 'RUS', fifaCode: 'RUS', confed: 'UEFA', ranking: 35, rating: 76 },
      { name: 'USA', shortName: 'USA', fifaCode: 'USA', confed: 'CONCACAF', ranking: 11, rating: 81 },
      { name: 'Mexico', shortName: 'MEX', fifaCode: 'MEX', confed: 'CONCACAF', ranking: 15, rating: 80 },
      { name: 'Canada', shortName: 'CAN', fifaCode: 'CAN', confed: 'CONCACAF', ranking: 48, rating: 75 },
      { name: 'Costa Rica', shortName: 'CRC', fifaCode: 'CRC', confed: 'CONCACAF', ranking: 52, rating: 73 },
      { name: 'Panama', shortName: 'PAN', fifaCode: 'PAN', confed: 'CONCACAF', ranking: 41, rating: 74 },
      { name: 'Jamaica', shortName: 'JAM', fifaCode: 'JAM', confed: 'CONCACAF', ranking: 55, rating: 72 },
      { name: 'Honduras', shortName: 'HON', fifaCode: 'HON', confed: 'CONCACAF', ranking: 76, rating: 67 },
      { name: 'El Salvador', shortName: 'SLV', fifaCode: 'SLV', confed: 'CONCACAF', ranking: 78, rating: 66 },
      { name: 'Haiti', shortName: 'HAI', fifaCode: 'HAI', confed: 'CONCACAF', ranking: 89, rating: 64 },
      { name: 'Curacao', shortName: 'CUW', fifaCode: 'CUW', confed: 'CONCACAF', ranking: 90, rating: 63 },
      { name: 'Trinidad and Tobago', shortName: 'TRI', fifaCode: 'TRI', confed: 'CONCACAF', ranking: 98, rating: 61 },
      { name: 'Guatemala', shortName: 'GUA', fifaCode: 'GUA', confed: 'CONCACAF', ranking: 108, rating: 59 },
      { name: 'Nicaragua', shortName: 'NCA', fifaCode: 'NCA', confed: 'CONCACAF', ranking: 134, rating: 52 },
      { name: 'Suriname', shortName: 'SUR', fifaCode: 'SUR', confed: 'CONCACAF', ranking: 143, rating: 50 },
      { name: 'Antigua and Barbuda', shortName: 'ATG', fifaCode: 'ATG', confed: 'CONCACAF', ranking: 142, rating: 50 },
      { name: 'Dominican Republic', shortName: 'DOM', fifaCode: 'DOM', confed: 'CONCACAF', ranking: 150, rating: 48 },
      { name: 'Cuba', shortName: 'CUB', fifaCode: 'CUB', confed: 'CONCACAF', ranking: 169, rating: 43 },
      { name: 'Bermuda', shortName: 'BER', fifaCode: 'BER', confed: 'CONCACAF', ranking: 171, rating: 42 },
      { name: 'Puerto Rico', shortName: 'PUR', fifaCode: 'PUR', confed: 'CONCACAF', ranking: 160, rating: 46 },
      { name: 'Guyana', shortName: 'GUY', fifaCode: 'GUY', confed: 'CONCACAF', ranking: 157, rating: 47 },
      { name: 'Belize', shortName: 'BLZ', fifaCode: 'BLZ', confed: 'CONCACAF', ranking: 182, rating: 38 },
      { name: 'Barbados', shortName: 'BRB', fifaCode: 'BRB', confed: 'CONCACAF', ranking: 178, rating: 39 },
      { name: 'Saint Kitts and Nevis', shortName: 'SKN', fifaCode: 'SKN', confed: 'CONCACAF', ranking: 147, rating: 49 },
      { name: 'Saint Lucia', shortName: 'LCA', fifaCode: 'LCA', confed: 'CONCACAF', ranking: 167, rating: 44 },
      { name: 'Saint Vincent and the Grenadines', shortName: 'VIN', fifaCode: 'VIN', confed: 'CONCACAF', ranking: 173, rating: 41 },
      { name: 'Grenada', shortName: 'GRN', fifaCode: 'GRN', confed: 'CONCACAF', ranking: 174, rating: 40 },
      { name: 'Dominica', shortName: 'DMA', fifaCode: 'DMA', confed: 'CONCACAF', ranking: 180, rating: 39 },
      { name: 'Cayman Islands', shortName: 'CAY', fifaCode: 'CAY', confed: 'CONCACAF', ranking: 197, rating: 32 },
      { name: 'Montserrat', shortName: 'MSR', fifaCode: 'MSR', confed: 'CONCACAF', ranking: 176, rating: 40 },
      { name: 'Bahamas', shortName: 'BAH', fifaCode: 'BAH', confed: 'CONCACAF', ranking: 202, rating: 30 },
      { name: 'Aruba', shortName: 'ARU', fifaCode: 'ARU', confed: 'CONCACAF', ranking: 193, rating: 34 },
      { name: 'Turks and Caicos Islands', shortName: 'TCA', fifaCode: 'TCA', confed: 'CONCACAF', ranking: 206, rating: 28 },
      { name: 'US Virgin Islands', shortName: 'VIR', fifaCode: 'VIR', confed: 'CONCACAF', ranking: 208, rating: 27 },
      { name: 'British Virgin Islands', shortName: 'VGB', fifaCode: 'VGB', confed: 'CONCACAF', ranking: 207, rating: 27 },
      { name: 'Anguilla', shortName: 'AIA', fifaCode: 'AIA', confed: 'CONCACAF', ranking: 209, rating: 26 },
      { name: 'French Guiana', shortName: 'GUF', fifaCode: 'GUF', confed: 'CONCACAF', ranking: 210, rating: 50 },
      { name: 'Martinique', shortName: 'MTQ', fifaCode: 'MTQ', confed: 'CONCACAF', ranking: 211, rating: 52 },
      { name: 'Guadeloupe', shortName: 'GLP', fifaCode: 'GLP', confed: 'CONCACAF', ranking: 212, rating: 50 },
      { name: 'Bonaire', shortName: 'BOE', fifaCode: 'BOE', confed: 'CONCACAF', ranking: 213, rating: 30 },
      { name: 'Saint Martin', shortName: 'SMT', fifaCode: 'SMT', confed: 'CONCACAF', ranking: 214, rating: 28 },
      { name: 'Sint Maarten', shortName: 'SXM', fifaCode: 'SXM', confed: 'CONCACAF', ranking: 215, rating: 27 },
      { name: 'Morocco', shortName: 'MAR', fifaCode: 'MAR', confed: 'CAF', ranking: 12, rating: 84 },
      { name: 'Senegal', shortName: 'SEN', fifaCode: 'SEN', confed: 'CAF', ranking: 20, rating: 81 },
      { name: 'Nigeria', shortName: 'NGA', fifaCode: 'NGA', confed: 'CAF', ranking: 28, rating: 78 },
      { name: 'Egypt', shortName: 'EGY', fifaCode: 'EGY', confed: 'CAF', ranking: 34, rating: 76 },
      { name: 'Ivory Coast', shortName: 'CIV', fifaCode: 'CIV', confed: 'CAF', ranking: 37, rating: 75 },
      { name: 'Tunisia', shortName: 'TUN', fifaCode: 'TUN', confed: 'CAF', ranking: 41, rating: 74 },
      { name: 'Algeria', shortName: 'ALG', fifaCode: 'ALG', confed: 'CAF', ranking: 43, rating: 74 },
      { name: 'Mali', shortName: 'MLI', fifaCode: 'MLI', confed: 'CAF', ranking: 47, rating: 72 },
      { name: 'Cameroon', shortName: 'CMR', fifaCode: 'CMR', confed: 'CAF', ranking: 51, rating: 71 },
      { name: 'South Africa', shortName: 'RSA', fifaCode: 'RSA', confed: 'CAF', ranking: 58, rating: 69 },
      { name: 'Burkina Faso', shortName: 'BFA', fifaCode: 'BFA', confed: 'CAF', ranking: 61, rating: 68 },
      { name: 'DR Congo', shortName: 'COD', fifaCode: 'COD', confed: 'CAF', ranking: 63, rating: 67 },
      { name: 'Cape Verde', shortName: 'CPV', fifaCode: 'CPV', confed: 'CAF', ranking: 65, rating: 66 },
      { name: 'Ghana', shortName: 'GHA', fifaCode: 'GHA', confed: 'CAF', ranking: 67, rating: 65 },
      { name: 'Guinea', shortName: 'GUI', fifaCode: 'GUI', confed: 'CAF', ranking: 76, rating: 64 },
      { name: 'Equatorial Guinea', shortName: 'EQG', fifaCode: 'EQG', confed: 'CAF', ranking: 79, rating: 63 },
      { name: 'Gabon', shortName: 'GAB', fifaCode: 'GAB', confed: 'CAF', ranking: 84, rating: 62 },
      { name: 'Zambia', shortName: 'ZAM', fifaCode: 'ZAM', confed: 'CAF', ranking: 87, rating: 61 },
      { name: 'Uganda', shortName: 'UGA', fifaCode: 'UGA', confed: 'CAF', ranking: 92, rating: 60 },
      { name: 'Angola', shortName: 'ANG', fifaCode: 'ANG', confed: 'CAF', ranking: 94, rating: 60 },
      { name: 'Benin', shortName: 'BEN', fifaCode: 'BEN', confed: 'CAF', ranking: 97, rating: 59 },
      { name: 'Namibia', shortName: 'NAM', fifaCode: 'NAM', confed: 'CAF', ranking: 106, rating: 57 },
      { name: 'Mauritania', shortName: 'MTN', fifaCode: 'MTN', confed: 'CAF', ranking: 105, rating: 57 },
      { name: 'Madagascar', shortName: 'MAD', fifaCode: 'MAD', confed: 'CAF', ranking: 109, rating: 56 },
      { name: 'Mozambique', shortName: 'MOZ', fifaCode: 'MOZ', confed: 'CAF', ranking: 110, rating: 56 },
      { name: 'Kenya', shortName: 'KEN', fifaCode: 'KEN', confed: 'CAF', ranking: 111, rating: 56 },
      { name: 'Congo', shortName: 'CGO', fifaCode: 'CGO', confed: 'CAF', ranking: 112, rating: 55 },
      { name: 'Togo', shortName: 'TOG', fifaCode: 'TOG', confed: 'CAF', ranking: 116, rating: 54 },
      { name: 'Tanzania', shortName: 'TAN', fifaCode: 'TAN', confed: 'CAF', ranking: 119, rating: 53 },
      { name: 'Guinea-Bissau', shortName: 'GNB', fifaCode: 'GNB', confed: 'CAF', ranking: 118, rating: 53 },
      { name: 'Zimbabwe', shortName: 'ZIM', fifaCode: 'ZIM', confed: 'CAF', ranking: 124, rating: 52 },
      { name: 'Malawi', shortName: 'MWI', fifaCode: 'MWI', confed: 'CAF', ranking: 122, rating: 52 },
      { name: 'Libya', shortName: 'LBY', fifaCode: 'LBY', confed: 'CAF', ranking: 120, rating: 53 },
      { name: 'Comoros', shortName: 'COM', fifaCode: 'COM', confed: 'CAF', ranking: 117, rating: 54 },
      { name: 'Sierra Leone', shortName: 'SLE', fifaCode: 'SLE', confed: 'CAF', ranking: 126, rating: 51 },
      { name: 'Sudan', shortName: 'SDN', fifaCode: 'SDN', confed: 'CAF', ranking: 127, rating: 51 },
      { name: 'Central African Republic', shortName: 'CTA', fifaCode: 'CTA', confed: 'CAF', ranking: 129, rating: 50 },
      { name: 'Niger', shortName: 'NIG', fifaCode: 'NIG', confed: 'CAF', ranking: 128, rating: 50 },
      { name: 'Rwanda', shortName: 'RWA', fifaCode: 'RWA', confed: 'CAF', ranking: 131, rating: 49 },
      { name: 'Gambia', shortName: 'GAM', fifaCode: 'GAM', confed: 'CAF', ranking: 130, rating: 50 },
      { name: 'Burundi', shortName: 'BDI', fifaCode: 'BDI', confed: 'CAF', ranking: 140, rating: 47 },
      { name: 'Ethiopia', shortName: 'ETH', fifaCode: 'ETH', confed: 'CAF', ranking: 145, rating: 46 },
      { name: 'Botswana', shortName: 'BOT', fifaCode: 'BOT', confed: 'CAF', ranking: 146, rating: 46 },
      { name: 'Liberia', shortName: 'LBR', fifaCode: 'LBR', confed: 'CAF', ranking: 152, rating: 45 },
      { name: 'Eswatini', shortName: 'SWZ', fifaCode: 'SWZ', confed: 'CAF', ranking: 148, rating: 45 },
      { name: 'Lesotho', shortName: 'LES', fifaCode: 'LES', confed: 'CAF', ranking: 149, rating: 45 },
      { name: 'South Sudan', shortName: 'SSD', fifaCode: 'SSD', confed: 'CAF', ranking: 167, rating: 41 },
      { name: 'Mauritius', shortName: 'MRI', fifaCode: 'MRI', confed: 'CAF', ranking: 177, rating: 39 },
      { name: 'Chad', shortName: 'CHA', fifaCode: 'CHA', confed: 'CAF', ranking: 176, rating: 39 },
      { name: 'Sao Tome and Principe', shortName: 'STP', fifaCode: 'STP', confed: 'CAF', ranking: 191, rating: 35 },
      { name: 'Djibouti', shortName: 'DJI', fifaCode: 'DJI', confed: 'CAF', ranking: 192, rating: 34 },
      { name: 'Seychelles', shortName: 'SEY', fifaCode: 'SEY', confed: 'CAF', ranking: 199, rating: 31 },
      { name: 'Eritrea', shortName: 'ERI', fifaCode: 'ERI', confed: 'CAF', ranking: 200, rating: 30 },
      { name: 'Somalia', shortName: 'SOM', fifaCode: 'SOM', confed: 'CAF', ranking: 198, rating: 31 },
      { name: 'Japan', shortName: 'JPN', fifaCode: 'JPN', confed: 'AFC', ranking: 18, rating: 83 },
      { name: 'Iran', shortName: 'IRN', fifaCode: 'IRN', confed: 'AFC', ranking: 20, rating: 81 },
      { name: 'South Korea', shortName: 'KOR', fifaCode: 'KOR', confed: 'AFC', ranking: 22, rating: 80 },
      { name: 'Australia', shortName: 'AUS', fifaCode: 'AUS', confed: 'AFC', ranking: 23, rating: 79 },
      { name: 'Qatar', shortName: 'QAT', fifaCode: 'QAT', confed: 'AFC', ranking: 34, rating: 76 },
      { name: 'Saudi Arabia', shortName: 'KSA', fifaCode: 'KSA', confed: 'AFC', ranking: 53, rating: 71 },
      { name: 'Iraq', shortName: 'IRQ', fifaCode: 'IRQ', confed: 'AFC', ranking: 59, rating: 69 },
      { name: 'Uzbekistan', shortName: 'UZB', fifaCode: 'UZB', confed: 'AFC', ranking: 66, rating: 66 },
      { name: 'UAE', shortName: 'UAE', fifaCode: 'UAE', confed: 'AFC', ranking: 69, rating: 65 },
      { name: 'Jordan', shortName: 'JOR', fifaCode: 'JOR', confed: 'AFC', ranking: 71, rating: 64 },
      { name: 'Oman', shortName: 'OMA', fifaCode: 'OMA', confed: 'AFC', ranking: 80, rating: 62 },
      { name: 'Bahrain', shortName: 'BHR', fifaCode: 'BHR', confed: 'AFC', ranking: 82, rating: 62 },
      { name: 'China', shortName: 'CHN', fifaCode: 'CHN', confed: 'AFC', ranking: 88, rating: 61 },
      { name: 'Syria', shortName: 'SYR', fifaCode: 'SYR', confed: 'AFC', ranking: 89, rating: 60 },
      { name: 'Palestine', shortName: 'PLE', fifaCode: 'PLE', confed: 'AFC', ranking: 93, rating: 60 },
      { name: 'Tajikistan', shortName: 'TJK', fifaCode: 'TJK', confed: 'AFC', ranking: 99, rating: 58 },
      { name: 'Thailand', shortName: 'THA', fifaCode: 'THA', confed: 'AFC', ranking: 101, rating: 58 },
      { name: 'Kyrgyzstan', shortName: 'KGZ', fifaCode: 'KGZ', confed: 'AFC', ranking: 104, rating: 57 },
      { name: 'Vietnam', shortName: 'VIE', fifaCode: 'VIE', confed: 'AFC', ranking: 115, rating: 54 },
      { name: 'North Korea', shortName: 'PRK', fifaCode: 'PRK', confed: 'AFC', ranking: 118, rating: 53 },
      { name: 'Lebanon', shortName: 'LBN', fifaCode: 'LBN', confed: 'AFC', ranking: 120, rating: 52 },
      { name: 'India', shortName: 'IND', fifaCode: 'IND', confed: 'AFC', ranking: 121, rating: 52 },
      { name: 'Malaysia', shortName: 'MAS', fifaCode: 'MAS', confed: 'AFC', ranking: 138, rating: 48 },
      { name: 'Kuwait', shortName: 'KUW', fifaCode: 'KUW', confed: 'AFC', ranking: 139, rating: 48 },
      { name: 'Philippines', shortName: 'PHI', fifaCode: 'PHI', confed: 'AFC', ranking: 141, rating: 47 },
      { name: 'Turkmenistan', shortName: 'TKM', fifaCode: 'TKM', confed: 'AFC', ranking: 143, rating: 46 },
      { name: 'Indonesia', shortName: 'IDN', fifaCode: 'IDN', confed: 'AFC', ranking: 134, rating: 49 },
      { name: 'Afghanistan', shortName: 'AFG', fifaCode: 'AFG', confed: 'AFC', ranking: 151, rating: 44 },
      { name: 'Singapore', shortName: 'SGP', fifaCode: 'SGP', confed: 'AFC', ranking: 155, rating: 43 },
      { name: 'Myanmar', shortName: 'MYA', fifaCode: 'MYA', confed: 'AFC', ranking: 163, rating: 41 },
      { name: 'Yemen', shortName: 'YEM', fifaCode: 'YEM', confed: 'AFC', ranking: 156, rating: 42 },
      { name: 'Hong Kong', shortName: 'HKG', fifaCode: 'HKG', confed: 'AFC', ranking: 157, rating: 42 },
      { name: 'Chinese Taipei', shortName: 'TPE', fifaCode: 'TPE', confed: 'AFC', ranking: 159, rating: 42 },
      { name: 'Maldives', shortName: 'MDV', fifaCode: 'MDV', confed: 'AFC', ranking: 161, rating: 41 },
      { name: 'Nepal', shortName: 'NEP', fifaCode: 'NEP', confed: 'AFC', ranking: 175, rating: 38 },
      { name: 'Cambodia', shortName: 'CAM', fifaCode: 'CAM', confed: 'AFC', ranking: 179, rating: 37 },
      { name: 'Bangladesh', shortName: 'BAN', fifaCode: 'BAN', confed: 'AFC', ranking: 184, rating: 36 },
      { name: 'Bhutan', shortName: 'BHU', fifaCode: 'BHU', confed: 'AFC', ranking: 185, rating: 35 },
      { name: 'Macau', shortName: 'MAC', fifaCode: 'MAC', confed: 'AFC', ranking: 187, rating: 34 },
      { name: 'Mongolia', shortName: 'MNG', fifaCode: 'MNG', confed: 'AFC', ranking: 191, rating: 33 },
      { name: 'Laos', shortName: 'LAO', fifaCode: 'LAO', confed: 'AFC', ranking: 190, rating: 34 },
      { name: 'Brunei', shortName: 'BRU', fifaCode: 'BRU', confed: 'AFC', ranking: 194, rating: 32 },
      { name: 'Pakistan', shortName: 'PAK', fifaCode: 'PAK', confed: 'AFC', ranking: 195, rating: 31 },
      { name: 'Timor-Leste', shortName: 'TLS', fifaCode: 'TLS', confed: 'AFC', ranking: 198, rating: 30 },
      { name: 'Sri Lanka', shortName: 'SRI', fifaCode: 'SRI', confed: 'AFC', ranking: 204, rating: 28 },
      { name: 'Guam', shortName: 'GUM', fifaCode: 'GUM', confed: 'AFC', ranking: 205, rating: 28 },
      { name: 'New Zealand', shortName: 'NZL', fifaCode: 'NZL', confed: 'OFC', ranking: 104, rating: 57 },
      { name: 'Solomon Islands', shortName: 'SOL', fifaCode: 'SOL', confed: 'OFC', ranking: 132, rating: 49 },
      { name: 'Fiji', shortName: 'FIJ', fifaCode: 'FIJ', confed: 'OFC', ranking: 168, rating: 41 },
      { name: 'New Caledonia', shortName: 'NCL', fifaCode: 'NCL', confed: 'OFC', ranking: 158, rating: 43 },
      { name: 'Tahiti', shortName: 'TAH', fifaCode: 'TAH', confed: 'OFC', ranking: 162, rating: 42 },
      { name: 'Vanuatu', shortName: 'VAN', fifaCode: 'VAN', confed: 'OFC', ranking: 170, rating: 40 },
      { name: 'Papua New Guinea', shortName: 'PNG', fifaCode: 'PNG', confed: 'OFC', ranking: 165, rating: 41 },
      { name: 'Samoa', shortName: 'SAM', fifaCode: 'SAM', confed: 'OFC', ranking: 186, rating: 35 },
      { name: 'American Samoa', shortName: 'ASA', fifaCode: 'ASA', confed: 'OFC', ranking: 188, rating: 34 },
      { name: 'Cook Islands', shortName: 'COK', fifaCode: 'COK', confed: 'OFC', ranking: 189, rating: 34 },
      { name: 'Tonga', shortName: 'TGA', fifaCode: 'TGA', confed: 'OFC', ranking: 196, rating: 31 },
    ];

    const toInsert = teamsData.map((td) => ({
      name: td.name,
      shortName: td.shortName,
      fifaCode: td.fifaCode,
      confederation: {
        name: confedNames[td.confed] || td.confed,
        code: td.confed,
      },
      fifaRanking: td.ranking,
      simulationRating: td.rating,
      flagUrl: '',
      matchesPlayed: 0,
      wins: 0,
      draws: 0,
      losses: 0,
      goalsFor: 0,
      goalsAgainst: 0,
      internationalTitles: 0,
      createdAt: new Date(),
      updatedAt: new Date(),
    }));

    await teamColl.insertMany(toInsert);
    console.log(`Seeded ${toInsert.length} teams.`);
  } finally {
    await client.close();
  }
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
